Add CIS integration to CCMS
ministryofjustice/laa-architecture-as-code pull request #46
Opened 2020-11-06 14:11 UTC by oliverweighell

## What does this pull request do?

- Adds CIS system
- Adds the integration between CIS and CCMS
- The docs suggest that CIS does more than is included in this PR, but at least it shows the CCMS relationship in a basic way. 

## What is the intent behind these changes?
- To represent an integration from CCMS to another LAA system.

## Diagram
![structurizr-55246-ccms-context-container](https://user-images.githubusercontent.com/17312421/98375313-ddb84d80-2039-11eb-849a-2e00195af32e.png)

2020-11-06 14:17 UTC, oliverweighell commented
According to https://dsdmoj.atlassian.net/wiki/spaces/LGP/pages/1391691215/Payment+Run CIS still does more than this (including case management for complex cases and an integration step in the payments process between CWA, CCLF, CCR and CCMS). Is this true? I'm not sure on the freshness of these docs or the value in representing it all here though? Happy to look at adding more on CIS if others think it is worthwhile?

2020-11-06 18:17 UTC, heidar commented
> According to https://dsdmoj.atlassian.net/wiki/spaces/LGP/pages/1391691215/Payment+Run CIS does more than this (... complex cases and payments integration between CWA, CCLF, CCR and CCMS). Is this still true? I'm not sure on the freshness of these docs or the value in representing it all here? Happy to look at adding more on CIS if others think it is worthwhile though?

As far as I know this is still true, it's in line with my knowledge of CIS at least.

2020-11-06 18:18 UTC, heidar requested changes

2020-11-06 18:18 UTC, heidar commented on src/main/kotlin/model/CCMS.kt
> +      soa.uses(CIS.system, "imports invoices approved for payment from")
Can you merge these two into one `uses`? I think only the first one will show up on the C4 diagrams :( So if you can summarise the relationship in a single `uses` that'd be better.

2020-11-09 09:44 UTC, oliverweighell commented on src/main/kotlin/model/CCMS.kt
> +      soa.uses(CIS.system, "imports invoices approved for payment from")
Looks like it shows up in the container diagram but not the context one.

2020-11-09 09:45 UTC, oliverweighell commented on src/main/kotlin/model/CCMS.kt
> +      soa.uses(CIS.system, "imports invoices approved for payment from")
Now updated to use the single `uses` so that it will appear in both.
![structurizr-55246-ccms-context-container](https://user-images.githubusercontent.com/17312421/98525332-396c1c00-2270-11eb-9a26-a5d385965be6.png)
![structurizr-55246-ccms-context](https://user-images.githubusercontent.com/17312421/98525358-40932a00-2270-11eb-8132-74fda6469de8.png)

2020-11-09 10:07 UTC, heidar approved these changes
```
                __/___            
          _____/______|           
  _______/_____\_______\_____     
  \              < < <       |    
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
SHIP IT! :D

2020-11-09 10:13 UTC, merged