Add CWA integration with CCMS
ministryofjustice/laa-architecture-as-code pull request #47
Opened 2020-11-06 16:00 UTC by oliverweighell

## What does this pull request do?

- Adds CWA system with simple view
- Adds integration between CWA and CCMS as per issue #17 
- Capitalises CCMS relationship descriptions in line with convention elsewhere

## What is the intent behind these changes?
- To represent the relationship between CWA and CCMS as per issue #17 

## Diagrams

### CCMS context
![structurizr-55246-ccms-context](https://user-images.githubusercontent.com/17312421/98387218-0ac02c80-2049-11eb-9c42-dbb3b11e6942.png)

### CCMS container
![structurizr-55246-ccms-context-container](https://user-images.githubusercontent.com/17312421/98387152-f714c600-2048-11eb-8486-d23b19aa1701.png)

2020-11-06 18:21 UTC, heidar requested changes

2020-11-06 18:21 UTC, heidar commented on src/main/kotlin/model/CCMS.kt
> +      soa.uses(BenefitChecker.system, "Validates Universal Credit claimants via", "SOAP")
Can you also add a `system.uses(CWA.system)` to summarise the relationship between CCMS and CWA in one arrow? Otherwise the system diagram will only show the first one of these two arrows to CWA on the system diagram for CCMS.

See here for an example with Apply: https://github.com/ministryofjustice/laa-architecture-as-code/blob/main/src/main/kotlin/model/Apply.kt#L56

2020-11-09 10:08 UTC, oliverweighell commented on src/main/kotlin/model/CCMS.kt
> +      soa.uses(BenefitChecker.system, "Validates Universal Credit claimants via", "SOAP")
Thanks - added:
![structurizr-55246-ccms-context](https://user-images.githubusercontent.com/17312421/98527934-87ceea00-2273-11eb-9a34-62408ad0515e.png)

2020-11-09 10:09 UTC, heidar approved these changes
💯

2020-11-09 10:25 UTC, merged